"""因果机制声明、求值与快照接口。"""

from .intervention import (
    FOREVER,
    INTERVENTION_TARGET_SPACES,
    SINGLE,
    WINDOW,
    InterventionRecord,
    InterventionTimeline,
    NodeResolution,
    PlannedIntervention,
    default_duration,
)
from .intervention_engine import InterventionEvaluator, InterventionFrameExecutor
from .observe import (
    AGENT_WEATHER_PROTOCOL,
    RESEARCH_PROTOCOL,
    leaks_research_truth,
    observe,
)
from .registry import MechanismRegistry
from .trace import RandomAddress, TraceLog, TraceRecord
from .declaration import DeclarationError
from .fate_registry import (
    FATE_NAMESPACES_PATH,
    FateNamespaceEntry,
    FateNamespaceRegistry,
    load_fate_namespaces,
)
from .state_schema import (
    DECLARATION_PATH,
    SlotDeclaration,
    StateDeclaration,
    StateSlice,
    encode_state,
    load_declaration,
    state_digest,
)
from .spec import (
    AccessPolicy,
    DependencyWitness,
    ExogenousSourceSpec,
    InstanceDomain,
    MathMetadata,
    MechanismSpec,
    NodeSpec,
    ParameterBinding,
    ParameterSpec,
    ParentSpec,
    RandomBinding,
    StateOwnership,
    UpdateContract,
    ValueDomain,
)

__all__ = [
    "AccessPolicy",
    "DECLARATION_PATH",
    "DeclarationError",
    "DependencyWitness",
    "ExogenousSourceSpec",
    "FATE_NAMESPACES_PATH",
    "FateNamespaceEntry",
    "FateNamespaceRegistry",
    "InstanceDomain",
    "MathMetadata",
    "MechanismRegistry",
    "MechanismSpec",
    "NodeSpec",
    "ParameterBinding",
    "ParameterSpec",
    "ParentSpec",
    "RandomBinding",
    "SlotDeclaration",
    "StateDeclaration",
    "StateOwnership",
    "StateSlice",
    "UpdateContract",
    "ValueDomain",
    "INTERVENTION_TARGET_SPACES",
    "InterventionRecord",
    "InterventionTimeline",
    "NodeResolution",
    "PlannedIntervention",
    "InterventionEvaluator",
    "InterventionFrameExecutor",
    "RandomAddress",
    "TraceLog",
    "TraceRecord",
    "AGENT_WEATHER_PROTOCOL",
    "RESEARCH_PROTOCOL",
    "leaks_research_truth",
    "observe",
    "FOREVER",
    "SINGLE",
    "WINDOW",
    "default_duration",
    "encode_state",
    "load_declaration",
    "load_fate_namespaces",
    "state_digest",
]
